FROM python:3.8.16

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

CMD ["streamlit", "run", "src/music_rec_sys.py", "--server.port", "8501", "--server.enableCORS", "false"]
